### ISSUE TITLE
Automate Gradle and dependency updates

### ISSUE THREAD

**Issue by translatenix** [apple/pkl#728] opened 2024-10-23 08:30 UTC
The Pkl build keeps falling behind in terms of Gradle and dependency versions.
Manual updates take significant time. For example, Gradle wrapper files need to be verified manually.
It would be very helpful to set up a bot such as [Renovate](https://docs.renovatebot.com/) (my favorite) or [Dependabot](https://github.com/dependabot) that automates such updates by sending PRs that edit `libs.versions.toml` and Gradle lock files.

**Comment by StefMa** [comment] 2024-10-23 09:26
Duplicate of https://github.com/apple/pkl/issues/225

**Comment by holzensp** [comment] 2024-10-23 09:48
Closing as duplicate of #225, but yes, something we do want.

**Closed by holzensp** 2024-10-23 09:48 UTC
