### ISSUE TITLE
Cannot clone Git repo on Win10

### ISSUE THREAD

**Issue by CudaText-addons** [apple/pkl#410] opened 2024-04-08 18:56 UTC
```
Microsoft Windows [Version 10.0.19045.4170]
(c) Microsoft Corporation. All rights reserved.

C:\Work>git clone https://github.com/apple/pkl
Cloning into 'pkl'...
remote: Enumerating objects: 6656, done.
remote: Counting objects: 100% (1437/1437), done.
remote: Compressing objects: 100% (449/449), done.
remote: Total 6656 (delta 1037), reused 1047 (delta 967), pack-reused 5219
Receiving objects: 100% (6656/6656), 3.51 MiB | 6.07 MiB/s, done.
Resolving deltas: 100% (2506/2506), done.
error: invalid path 'pkl-doc/src/test/files/DocGeneratorTest/output/data/localhost:0/birds/0.5.0/Bird/index.js'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by translatenix** [comment] 2024-04-08 23:01
Duplicate of https://github.com/apple/pkl/issues/99.

**Comment by bioball** [comment] 2024-04-09 00:01
Closed as duplicate

**Closed by bioball** 2024-04-09 00:01 UTC
