### ISSUE TITLE
Weird error trying to run examples in kotlin

### ISSUE THREAD

**Issue by nwsent** [apple/pkl#115] opened 2024-02-11 15:30 UTC
I have explained it here: https://github.com/apple/pkl-jvm-examples/issues/6

**Comment by translatenix** [comment] 2024-02-14 01:34
The likely reason is that Pkl doesn’t yet support Windows. But I think it’s on the roadmap (see #20).

**Comment by bioball** [comment] 2024-02-14 01:43
Yup, @translatenix is right. We're aiming to support Windows in our next release (0.26, targeted for June).

For now, to use Pkl on Windows, the best method is to run it via WSL.

Closing this as a duplicate of #20

**Closed by bioball** 2024-02-14 01:43 UTC

**Comment by mitchcapper** [comment] 2024-02-23 04:28
You can likely do what you want currently see https://github.com/apple/pkl-jvm-examples/pull/9  and #237 it is for java codegen but I can't imagine it is any different.  For one your absolute windows paths starting with `c:` will likely not work, and for another all slashes must be forward slashes.
